-- TODO: Buscar como implementar pgTAP

INSERT INTO brands (name, description) VALUES
('Apple', 'Innovative technology and electronics company.'),
('Samsung', 'Global leader in electronics and home appliances.'),
('Microsoft', 'Technology and software giant.'),
('Google', 'Search engine and technology pioneer.'),
('Amazon', 'E-commerce and cloud computing leader.'),
('Nike', 'World-famous sportswear and footwear brand.'),
('Adidas', 'Sportswear and lifestyle apparel brand.'),
('Sony', 'Electronics, gaming, and entertainment company.'),
('Coca-Cola', 'Iconic beverage company.'),
('Pepsi', 'Global soft drink and snack brand.'),
('Toyota', 'Leading Japanese automotive manufacturer.'),
('Honda', 'Innovative car and motorcycle brand.'),
('BMW', 'Luxury German automobile manufacturer.'),
('Mercedes-Benz', 'Prestigious German automotive brand.'),
('Tesla', 'Electric vehicle and clean energy company.'),
('Ford', 'American automobile manufacturer with a long history.'),
('Chevrolet', 'Popular American car brand.'),
('KFC', 'Famous for its fried chicken worldwide.'),
('McDonald''s', 'Global fast-food chain.'),
('Burger King', 'Well-known international fast-food restaurant.'),
('Subway', 'Largest sandwich and fast-food chain.'),
('Starbucks', 'Renowned coffeehouse chain.'),
('Nestle', 'Global food and beverage company.'),
('Procter & Gamble', 'Consumer goods and hygiene products company.'),
('Unilever', 'Multinational consumer goods company.'),
('L''Oreal', 'World leader in beauty and cosmetics.'),
('Chanel', 'Iconic luxury fashion and fragrance brand.'),
('Gucci', 'High-end fashion and leather goods company.'),
('Prada', 'Prestigious Italian fashion house.'),
('Versace', 'Luxury fashion brand from Italy.'),
('Louis Vuitton', 'World-famous luxury brand for bags and accessories.'),
('Rolex', 'Luxury Swiss watchmaker.'),
('Omega', 'Prestigious Swiss watch brand.'),
('Dell', 'American multinational computer technology company.'),
('HP', 'Leading provider of PCs and printers.'),
('Lenovo', 'Chinese multinational technology company.'),
('Asus', 'Innovative consumer electronics and tech company.'),
('Acer', 'Global PC and electronics manufacturer.'),
('Intel', 'Leader in semiconductor and computer chip production.'),
('AMD', 'Processor and graphics card manufacturer.'),
('NVIDIA', 'World leader in graphics and AI technology.'),
('Netflix', 'Popular streaming platform for movies and series.'),
('Spotify', 'Leading music streaming platform.'),
('Disney', 'Global entertainment and media conglomerate.'),
('Warner Bros', 'Famous film and television production studio.'),
('Universal Pictures', 'Major American film studio.'),
('Paramount', 'Renowned American film studio.'),
('IBM', 'Pioneering tech and cloud computing company.'),
('Oracle', 'Leader in enterprise software and database management.'),
('Salesforce', 'CRM and cloud-based solutions provider.'),
('Adobe', 'Leader in creative software solutions.'),
('Samsung Electronics', 'Division of Samsung focused on electronics.'),
('Panasonic', 'Global electronics manufacturer.'),
('Philips', 'Dutch multinational electronics company.'),
('LG Electronics', 'South Korean electronics and appliances company.'),
('Huawei', 'Chinese technology and smartphone company.'),
('Xiaomi', 'Chinese electronics and smart devices brand.'),
('OnePlus', 'Popular smartphone and tech company.'),
('Vivo', 'Chinese smartphone manufacturer.'),
('Oppo', 'Smartphone and consumer electronics brand.'),
('Realme', 'Emerging smartphone brand.'),
('TikTok', 'Popular short-form video platform.'),
('Instagram', 'Social media platform owned by Meta.'),
('Facebook', 'Pioneering social media platform by Meta.'),
('Twitter', 'Global microblogging and social networking site.'),
('Snapchat', 'Social media app with disappearing messages.'),
('Pinterest', 'Platform for inspiration and ideas.'),
('LinkedIn', 'Professional networking site.'),
('YouTube', 'Largest video-sharing platform owned by Google.'),
('Twitch', 'Popular live-streaming platform.'),
('Reddit', 'Online discussion and content-sharing platform.'),
('eBay', 'Global e-commerce and auction platform.'),
('PayPal', 'Digital payment platform.'),
('Mastercard', 'Global payment and technology company.'),
('Visa', 'World leader in digital payments.'),
('American Express', 'Financial services and credit card provider.'),
('Stripe', 'Online payment processing company.'),
('Square', 'Digital payments and point-of-sale solutions.'),
('Shopify', 'E-commerce platform for businesses.'),
('Walmart', 'World''s largest retail corporation.'),
('Costco', 'Wholesale membership-based retailer.'),
('Target', 'American retail corporation.'),
('IKEA', 'Swedish multinational furniture and home goods retailer.'),
('Zara', 'Fast-fashion clothing retailer.'),
('H&M', 'Affordable fashion retailer.'),
('Uniqlo', 'Japanese clothing retailer.'),
('Forever 21', 'Youth-focused fashion brand.'),
('ASOS', 'Online fashion and cosmetic retailer.'),
('Shein', 'Online fast-fashion retailer.'),
('Puma', 'Global sportswear and lifestyle brand.'),
('Reebok', 'Sports footwear and apparel company.'),
('Under Armour', 'Performance apparel and footwear brand.'),
('The North Face', 'Outdoor clothing and gear company.'),
('Patagonia', 'Outdoor clothing and environmental advocacy brand.'),
('Columbia', 'Outdoor clothing and equipment company.'),
('Timberland', 'Renowned for boots and outdoor gear.'),
('Vans', 'Skateboarding and lifestyle shoe brand.');