INSERT INTO categories (name, description) VALUES
('Accesorios para Vehículos', 'Artículos y accesorios relacionados con vehículos, desde herramientas hasta componentes y repuestos.'),
('Agro', 'Productos y servicios relacionados con la agricultura, ganadería y la industria agroalimentaria.'),
('Alimentos y Bebidas', 'Todo lo relacionado con productos alimenticios y bebidas, desde comestibles hasta bebidas alcohólicas y no alcohólicas.'),
('Animales y Mascotas', 'Productos y servicios para el cuidado y bienestar de animales y mascotas, incluyendo alimentos y accesorios.'),
('Antigüedades y Colecciones', 'Artículos antiguos, coleccionables y objetos de valor histórico o cultural.'),
('Arte, Librería y Cordonería', 'Material artístico, libros, y artículos de cordonería y papelería.'),
('Autos, Motos y Otros', 'Vehículos motorizados, tanto autos como motocicletas y otros medios de transporte.'),
('Bebés', 'Productos para el cuidado, alimentación y entretenimiento de bebés y niños pequeños.'),
('Belleza y Cuidado Personal', 'Cosméticos, productos de higiene personal, cuidado de la piel, el cabello y belleza en general.'),
('Cámaras y Accesorios', 'Cámaras fotográficas, cámaras de video y accesorios relacionados para capturar imágenes y videos.'),
('Celulares y Telefonía', 'Móviles, accesorios y servicios relacionados con la telefonía móvil y fija.'),
('Computación', 'Productos y servicios relacionados con computadoras, software y accesorios tecnológicos.'),
('Consolas y Videojuegos', 'Consolas de videojuegos, juegos y accesorios relacionados.'),
('Construcción', 'Materiales y herramientas para la construcción y renovación de edificaciones y obras.'),
('Deportes y Fitness', 'Productos para la práctica deportiva, ejercicio físico y bienestar, incluyendo equipos y ropa.'),
('Electrodomésticos', 'Aparatos electrónicos y electrodomésticos para el hogar, como refrigeradores, lavadoras y microondas.'),
('Electrónica, Audio y Video', 'Equipos electrónicos, audio, video y accesorios para el hogar o uso personal.'),
('Entradas para Eventos', 'Boletos y entradas para eventos como conciertos, deportes, teatros, entre otros.'),
('Herramientas', 'Herramientas manuales y eléctricas para trabajo en casa, en la oficina o en proyectos industriales.'),
('Hogar y Muebles', 'Muebles y artículos decorativos para el hogar, desde salas hasta dormitorios y accesorios.'),
('Industrias y Oficinas', 'Productos y suministros destinados al uso industrial y en oficinas, desde maquinaria hasta mobiliario.'),
('Inmuebles', 'Bienes raíces y propiedades, como viviendas, terrenos y locales comerciales.'),
('Instrumentos Musicales', 'Instrumentos y accesorios para la práctica musical, como guitarras, pianos, micrófonos, entre otros.'),
('Juegos y Juguetes', 'Juguetes y juegos para niños y adultos, desde tradicionales hasta electrónicos.'),
('Libros, Revistas y Comics', 'Publicaciones literarias, educativas, de entretenimiento, incluyendo cómics, novelas y revistas.'),
('Música y Películas', 'Material musical y películas en diferentes formatos, incluyendo discos y DVDs.'),
('Relojes y Joyas', 'Relojes, joyas y accesorios de lujo o de uso diario, como pulseras, anillos y cadenas.'),
('Salud y Equipamiento Médico', 'Productos y equipos médicos para el cuidado de la salud y bienestar, desde medicamentos hasta maquinaria.'),
('Servicios', 'Servicios profesionales y personales que incluyen reparaciones, asesorías y otros tipos de asistencia.'),
('Souvenirs, Cotillón y Fiestas', 'Artículos para eventos y celebraciones, como decoraciones, souvenirs y accesorios para fiestas.'),
('Vestuario y Calzado', 'Ropa y calzado para todas las edades y géneros, desde casual hasta formal y deportivo.'),
('Otras Categorías', 'Cualquier categoría que no encaje en las anteriores, para artículos diversos y únicos.');